server:
  port: 8090
  servlet:
    context-path: /api

spring:
  application:
    name: prospection-backend

  # Database Configuration
  datasource:
    url: jdbc:postgresql://localhost:5432/prospection_db
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver

  # JPA Configuration
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

# JWT Configuration
jwt:
  secret: mySecretKey123456789012345678901234567890
  expiration: 86400000 # 24 hours in milliseconds

# CORS Configuration
cors:
  allowed-origins:
    - http://localhost:5173
    - http://localhost:3000
  allowed-methods: GET,POST,PUT,DELETE,OPTIONS
  allowed-headers: "*"
  allow-credentials: true

# Logging
logging:
  level:
    com.prospection: DEBUG
    org.springframework.security: DEBUG