server:
  port: 8090
  servlet:
    context-path: /api

spring:
  application:
    name: prospection-backend


  datasource:
    url: jdbc:postgresql://localhost:5432/prospection_db
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver


  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true


jwt:
  secret: mySecretKey123456789012345678901234567890
  expiration: 900000 # 15 min
  refresh-expiration: 604800000 #7 jours


cors:
  allowed-origins:
    - http://localhost:5173
    - http://localhost:3000
  allowed-methods: GET,POST,PUT,DELETE,OPTIONS
  allowed-headers: "*"
  allow-credentials: true


logging:
  level:
    com.prospection: DEBUG
    org.springframework.security: DEBUG